<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="Baburaoji Gholap College , Sangvi ,Pune" />
	<meta name="description" content="Baburaoji Gholap College , Sangvi ,Pune">
	<meta name="author" content="Baburaoji Gholap College , Sangvi ,Pune">
	<jsp:include page="title.jsp"></jsp:include>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
         <div style="border: 1px solid black;padding: 2px;margin: 12px;">
              <div class="row" >
                   <div class="col-sm-1" ></div>
                   <div class="col-sm-10" >
						<h4 style="margin-left: 20px; text-align: center;color: brown;" >Pune District Education Association's</h4>
						<h3 style="margin-left:100px;margin-right:20px;margin-top: 2px;padding-bottom: 2px;color:#43577B;font-weight: bold;">PROF. RAMKRISHNA MORE ARTS, COMMERCE &amp; SCIENCE COLLEGE</h3>
						<p  style="margin-left:20px;margin-right:20px;margin-top: 1px;padding-bottom: 2px; text-align: center; color: brown;">Akurdi, Pradhikaran, Pune - 411044 (Maharashtra) India</p>
						<div class="marquee" align="center">
	      					<p  class="headertxt" id="uni" style="color: green;">Affiliated to Savitribai Phule Pune University, Pune  |  Year of Establishment - 1992  |  ID No.: PU/PN/ASC/090/1992</p>
						</div>
				  </div>
				<div class="col-sm-1" ></div>
			</div>
			<hr style="border: 1px solid black;">
			<u><h3 style="margin-left:20px;margin-right:20px;margin-top: 2px;padding-bottom: 2px;color:#1c3561;font-weight: bold;text-align: center;">Intellectual Proper Rights Cell</h3></u>
			<br>
			<div class="row" >
                   <div class="col-sm-1" ></div>
                   <div class="col-sm-10" >
                    <p style="text-align: justify;font-weight: normal;margin-left: 3%;">
                    Intellectual Property (IP) is a category of property that includes intangible creation of human intellectual.Intellectual property provides assets like inventions, designs, software other creative and innovative ideas. IPR is granted to creators and owners of works that are results of human intellectual creativity. 
                    </p>
                     <p style="text-align: justify;font-weight: normal;margin-left: 3%;">
                     <b>Acts and rules of IPR are available on  </b><a href="http://www.ipindia.nic.in/resources.htm#acts" target="_blank">http://www.ipindia.nic.in/resources.htm#acts</a>
                      Prof. Ramkrishna More Arts, Commerce and Science College recognizes the importance of intellectual Property Rights of IP generated by its teachers and students. The college is committed to do all sorts of IP within its power and obligations to encourage innovations and creations of its faculty and students. IPR cell of Prof. Ramkrishna More Arts, Commerce and Science College established in June 2017.  The IPR cell of college provides support and guidance to faculty and students in protecting their inventions and creations. The activity of IPR cell of the college is in alignment of Government of India. 
                     
                    </p>
                        
                        <ul>
                             <li style="list-style-type:square;font-weight: bold;"><h4 style="color: #43577B;font-family: sans-serif; font-weight: bold;">The objectives of IPR cell are:-</h4>
                                   <ul style="margin-left: 10%;"> 
                                        <li>To promote academic freedom and safeguard the interests of faculty and students for the creation and invention;                   
                                        </li>
                                        <li>
                                         	To provide and other support to commercialize intellectual property;
                                        </li>
                                        <li>
                                           To provide help to apply for patents. 
                                        </li>
                                        
                                   </ul>
                                   
                             </li>
                             <li style="list-style-type:square;font-weight: bold;"><h4 style="color: #43577B;font-family: sans-serif; font-weight: bold;">Committee Member:-</h4>    
                                   <ul style="margin-left: 10%;"> 
                                        <li><strong>Committee Chairman</strong>
                                             <ul style="margin-left: 12%;">
                                                  <li>Dr. M. G. Chaskar (Principal)</li>
                                              </ul>
                                        </li>
                                   </ul>
                                    <ul style="margin-left: 10%;"> 
                                        <li><strong>Committee CO-ordinator</strong>
                                             <ul style="margin-left: 12%;">
                                                  <li>Dr. P. S. Kadam</li>
                                              </ul>
                                        </li>
                                   </ul>
                                   <ul style="margin-left: 10%;"> 
                                        <li><strong>Committee Member</strong>
                                             <ul style="margin-left: 12%;">
                                                  <li> Dr. Dinesh Amalnerkar (External Expert-Scientist)</li>
                                                  <li> Dr.Kedar Deobhankar (Industrial Expert) </li>
                                                  <li> Dr. M. Dhumal	</li>
                                                  <li> Dr. P. S. Tambade </li>
                                                  <li> Dr. D. R. Shinde	</li>
                                                  <li> Dr. B. G. Lobo </li>
                                              </ul>
                                        </li>
                                   </ul>
                             </li>
                             <br>
                            <li style="list-style-type:square;font-weight: bold;"><h4 style="color: #43577B;font-family: sans-serif; font-weight: bold;">Publication:-</h4>    
                                   <ul style="margin-left: 10%;list-style-type:none;"> 
                                        <li style="color: blue;"><strong>Intellectual Property Rights</strong>
                                        </li>
                                         <li style="font-weight: normal;">Snehvardhan Publication
                                        </li>
                                         <li style="font-weight: normal;">Editors: M. K. Dhumal, S. P. Dhumal
                                        </li>
                                   </ul>
                                  
                             </li>
                       </ul>
                       
                        <br><br>
                   
                   </div>
                   <div class="col-sm-1" ></div>
                   
            </div>
			
		</div>
</body>
</html>